### ISSUE TITLE
Require <-> include, arr

### ISSUE THREAD

**Issue by Matess** [4iz278/cviceni#3]
2x require

https://github.com/4iz278/cviceni/blob/master/02-retezce-soubory/02-include/index.php#L2

A další drobnost arr -> arr2

https://github.com/4iz278/cviceni/blob/master/02-retezce-soubory/02-array.php#L8

**Comment by vojir** [comment]
Chybu u vardumpu pole jsem opravil.

Co se Vám nelíbí na příkladu s include/require? Na Vámi zvýrazněném řádku je za příkazem require uveden vysvětlující komentář, nejedná se o žádnou duplicitu.
https://github.com/4iz278/cviceni/blob/master/02-retezce-soubory/02-include/index.php#L2

**Comment by Matess** [comment]
No pochopil jsem výklad tak, že require a include jsou prakticky identické kromě vyhození chyby, takže na tom řádku očekávám něco jako:

 require 'header.inc.php';//stejné jako **include**('header.inc.php');
NEBO
 **include** 'header.inc.php';//stejné jako require('header.inc.php');

Pokud jde ale o závorky, tak pardon.

**Comment by vojir** [comment]
Na daném řádku jde o to, že buď můžeme include/require zapsat jako příkaz (bez závorek):

``` php
require 'soubor';
```

nebo jako funkci:

``` php
require('soubor');
```

---

Rozdíl mezi includem a requirem je v tom, jako moc je daný soubor vyžadován - pokud není nalezen soubor vyžadovaný requirem, skript dál neběží.
